name: allstatistics
channels:
    - defaults
dependencies:
    - pip=20.2.2
    - python=3.8.5
    - pip:
        - black
        - ipywidgets
        - matplotlib==3.3.3
        - notebook==6.1.5
        - numba
        - numpy==1.19.1
        - pandas==1.1.1
        - scipy
        - tqdm
        - warnings
